<a href="https://colab.research.google.com/github/aktasceren/NumericalAnalysis/blob/main/cse317_hw01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sympy import diff, sin, exp
import numpy as np
import math
from sympy.abc import * 


x, a = symbols("x a")

#derivative of function
def der(expr, n):
    if n > 1:
        return der(diff(expr), n-1)
    return expr

def taylor_expansion(func, process):
    # process -= 1
    TaylorExpansion = func
    f = der(func, 2)
    for i in range(1, process):
        TaylorExpansion += pow(x-a, i)*der(f, i) / math.factorial(i)        
    return TaylorExpansion

TaylorExpansion = taylor_expansion(sin(2*a), 5)
#print("Taylor series expension where a = 0: ", TaylorExpansion)

TaylorExpansion = TaylorExpansion.subs([(x, math.pi/4), (a, 0)])
#print("Taylor series expansion for first five terms where x is pi/4 = ", TaylorExpansion)

#TaylorExpansion is calculated value
realValue = sin(2*(math.pi/4)) #real value of sin2x

print("\n-----1. Question-----\n")

#Absolute Error
AbsoluteError = abs(realValue- TaylorExpansion)
print("Absolute error: ", AbsoluteError)

#RelativeError

RelativeError = AbsoluteError/realValue
print("Relative Error:", RelativeError)

#Percentage Error
PercentageError = ((realValue - TaylorExpansion) / realValue) * 100
print("Percentage error: % ", PercentageError)




-----1. Question-----

Absolute error:  0.0751677707113496
Relative Error: 0.0751677707113496
Percentage error: %  7.51677707113496


In [2]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.5f}".format(x)})

def gauss_elimination(matrix, b):
    L = np.zeros((3, 3), float)
    x_vector = np.zeros((3, 1), float)
    #print("-----multipliers-----")
    
    for i in range(2):
        for j in range(3):
            if i == j:
                for k in range(j+1, 3):
                    multiplier = matrix[k][i]/matrix[i][i]
                    #print(multiplier)
                    matrix[k, :] = matrix[k, :] - multiplier*matrix[i, :]
                    b[k] = b[k]-multiplier*b[i]
                    
    #print("-----after elimination transformation----- \n\n-----matrix A-----")
    #print(matrix)
    #print("\n-----vector b-----")
    #print(b)
    #inverse = np.linalg.inv(matrix) 
    #print(matrix)
    
    print("-----After Back Substitution Phase-----\n\n-----vector x-----")
    #print(inverse.dot(b)) 
    x_vector[2] = b[2]/matrix[2][2]
    
    for i in range(1, -1, -1):
        eq = b[i]
        for j in range(i + 1, 3):
            eq = eq - matrix[i][j]*x_vector[j]
        x_vector[i] = eq / matrix[i][i]
    print(x_vector)

A1 = np.array([[2, -3, -1],
              [3, 2, -5],
              [2, 4, -1]], float)

B1 = np.array([[3],
             [-9],
             [-5]], float)

print("-----2. Question-----\n")
second_question = gauss_elimination(A1, B1)

-----2. Question-----

-----After Back Substitution Phase-----

-----vector x-----
[[0.65306]
 [-1.14286]
 [1.73469]]


In [3]:
def doolittles_decomposition(matrix, b):
    
    L= np.array([[1, 0, 0],
                 [1, 1, 0],
                 [1, 1, 1]], float)
    U= matrix
    
    for i in range(2):
        for j in range(3):
            if i == j:
                for k in range(j+1, 3):
                    multiplier = matrix[k][i]/matrix[i][i]
                    matrix[k, :] = matrix[k, :] - multiplier*matrix[i, :]
                    matrix[k][i]=multiplier
                    U[k][i] = 0
                    L[k][i] = multiplier
                    
    #print(matrix)
    #print("----L----")
    #print(L)
    y = np.linalg.inv(L).dot(b)
    #print("-----y-----")
    #print(y)
    #print("----U----")
    #print(U)
    x = np.linalg.inv(U).dot(y)
    print("----x----")
    print(x)
    
A3= np.array([[2.34, -4.10, 1.78], 
              [-1.98, 3.47, -2.22],
              [2.36, -15.17, 6.18]], float)

B3= np.array([[0.02],
              [-0.73],
              [-6.63]], float)

print("\n-----3. Question-----\n")
v = doolittles_decomposition(A3, B3)


-----3. Question-----

----x----
[[1.00000]
 [1.00000]
 [1.00000]]


In [4]:
def cholesky_decomposition(matrix, b):
    
    L = np.zeros((3, 3), float)
    
    for j in range(3):
        for i in range(3):
            sum_of_elements = 0
            #for diagonal terms
            if i == j:
                for k in range(j):
                    sum_of_elements += L[j][k] ** 2
                L[j][j] = math.sqrt(matrix[j][j] - sum_of_elements)                
            #for nondiagonal terms
            elif i > j:
                for k in range(j):
                    sum_of_elements += L[i][k] * L[j][k]
                L[i][j] = (matrix[i][j] - sum_of_elements) / L[j][j]
    #print("-----matrix L-----")
    #print(L)
    x_vector = lu_decomposition(L, b)
    print("\n-----x is equal-----")
    print(x_vector)


def transpose(matrix):
    transpose_of_matrix = np.zeros((3, 3), float)
    for i in range(3):
        for j in range(3):
            transpose_of_matrix[j][i] = matrix[i][j]
    #print("\n-----transpose of matrix L-----")
    #print(transpose_of_matrix)
    return transpose_of_matrix


def lu_decomposition(matrix, b):
    inverse_of_matrix = np.linalg.inv(matrix)
    inverse_of_transpose_of_matrix = np.linalg.inv(transpose(matrix))
    y = inverse_of_matrix.dot(b)
    #print("\n-----y is equal-----")
    #print(y)
    x = inverse_of_transpose_of_matrix.dot(y)
    return x


A2 = np.array([[1, 1, 1],
              [1, 2, 2],
              [1, 2, 3]])

B2 = np.array([[1],
              [1.5],
              [3]])

print("\n-----4. Question-----")
cholesky_decomposition(A2, B2)


-----4. Question-----

-----x is equal-----
[[0.50000]
 [-1.00000]
 [1.50000]]
